language: node_js
dist: bionic
node_js:
  - 14
cache:
  directories:
    - node_modules
on:
  branch: master

script:
  - node --version
  - yarn build
  - xvfb-run --auto-servernum yarn test

os:
  - linux

addons:
  chrome: stable
  apt:
    packages:
      - libnss3
      # These are required to run webkit
      - libwoff1
      - libopus0
      - libwebp6
      - libwebpdemux2
      - libenchant1c2a
      - libgudev-1.0-0
      - libsecret-1-0
      - libhyphen0
      - libgdk-pixbuf2.0-0
      - libegl1
      - libgles2
      - libevent-2.1-6
      - libnotify4
      - libxslt1.1
      - libvpx5
      # gstreamer and plugins to support video playback in WebKit.
      - gstreamer1.0-gl
      - gstreamer1.0-plugins-base
      - gstreamer1.0-plugins-good
      - gstreamer1.0-plugins-bad
      # This is required to run chromium
      - libgbm1
      # this is needed for running headful tests
      - xvfb

before_install:
  # Info about OS
  - uname
  #- if [[ `node -v` = v14* ]]; then npm i -g npx; fi
  - npx --version
  # Enable user namespace cloning
  - if [[ `uname` = "Linux" ]]; then sysctl kernel.unprivileged_userns_clone=1; fi
  # Launch XVFB
  - if [[ `uname` = "Linux" ]]; then export DISPLAY=:99.0; fi

before_script:
  - npm install --no-save playwright@1.18.1
