language: node_js
dist: bionic
node_js:
  - 14
cache:
  directories:
    - node_modules
script:
  - yarn test:ci
  - yarn build
on:
  branch: master

addons:
  apt:
    packages:
      # These are required to run webkit
      - libwoff1
      - libopus0
      - libwebp6
      - libwebpdemux2
      - libenchant1c2a
      - libgudev-1.0-0
      - libsecret-1-0
      - libhyphen0
      - libgdk-pixbuf2.0-0
      - libegl1
      - libgles2
      - libevent-2.1-6
      - libnotify4
      - libxslt1.1
      - libvpx5
      # gstreamer and plugins to support video playback in WebKit.
      - gstreamer1.0-gl
      - gstreamer1.0-plugins-base
      - gstreamer1.0-plugins-good
      - gstreamer1.0-plugins-bad
      # This is required to run chromium
      - libgbm1
      # this is needed for running headful tests
      - xvfb

# allow headful tests
before_install:
  # Enable user namespace cloning
  - 'sysctl kernel.unprivileged_userns_clone=1'
  # Launch XVFB
  - 'export DISPLAY=:99.0'
  - 'sh -e /etc/init.d/xvfb start'
